swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: "#/definitions/Login"
      produces:
        - application/json
      responses:
        "200":
          description: Login Successfully
          schema:
            $ref: "#/definitions/LoginResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: "#/definitions/User"
      produces:
        - application/json
      responses:
        "200":
          description: Signup Successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: "#/definitions/UserProfile"
      produces:
        - application/json
      responses:
        "200":
          description: User profile updated successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
 
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Transaction id API
      description: |
        API for retrieving details of a specific transaction by specifying the transaction ID.
        Requires Bearer JWT token authorization in the request header to ensure that only authenticated users can access their individual transactions.
        You can specify the transaction ID in the URL to get details of that particular transaction.
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: id
          type: integer
          required: true
          description: The transaction id
      produces:
        - application/json
      responses:
        "200":
          schema:
            $ref: "#/definitions/Transaction"
          description: Transaction retrieved successfully
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Add Note to Transaction
      description: |
        API for adding a note to a specific transaction by providing the transaction ID and note data.
        Allows users to associate custom notes with their transactions, useful for adding comments or additional descriptions.
        Requires Bearer JWT token authorization for security.
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: id
          type: string
          description: Transaction ID
          required: true
        - in: body
          name: body
          description: Notes payload
          required: true
          schema:
            $ref: "#/definitions/UserTransaction"
      produces:
        - application/json
      responses:
        "200":
          schema:
            $ref: "#/definitions/Transaction"
          description: Note added successfully
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Update Transaction Note
      description: |
        API for updating the note of a specific transaction by providing the transaction ID and note data.
        Allows users to update the data of the note associated with a particular transaction.
        Requires Bearer JWT token authorization for security.
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: id
          type: string
          description: Transaction ID
          required: true
        - in: body
          name: body
          description: Notes payload
          required: true
          schema:
            $ref: "#/definitions/UserTransaction"
      produces:
        - application/json
      responses:
        "200":
          schema:
            $ref: "#/definitions/Transaction"
          description: Note updated successfully
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Delete Transaction Note
      description: |
        API for deleting the note of a specific transaction by providing the transaction ID.
        Allows users to remove a note previously associated with a transaction, if necessary.
        Bearer JWT token authorization is required to access this feature.
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: id
          type: string
          description: Transaction ID
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: Transaction note deleted successfully
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/account/{accountId}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Account Transactions API
      description: |
        API for fetching transactions for a specific account with optional type filtering.
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: accountId
          type: string
          description: The account id
          required: true
        - in: query
          name: type
          type: string
          description: Transaction type (cheque, epargne, carte_credit, etc.)
        - in: query
          name: dateStart
          type: string
          description: Date start type (format: yyyy-mm-dd)
        - in: query
          name: dateEnd
          type: string
          description: Date end type (format: yyyy-mm-dd)
      produces:
        - application/json
      responses:
        "200":
          description: Transactions retrieved successfully
          schema:
            $ref: "#/definitions/Transactions"
        "400":
          description: Transactions not found
        "500":
          description: Internal Server Error
  /user/account/{accountId}/transactions/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Transaction id API
      description: |
        API for retrieving details of a specific transaction by specifying the transaction ID.
        Requires Bearer JWT token authorization in the request header to ensure that only authenticated users can access their individual transactions.
        You can specify the transaction ID in the URL to get details of that particular transaction.
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: accountId
          type: integer
          required: true
          description: The account id
        - in: path
          name: transactionId
          type: integer
          required: true
          description: The transaction id
      produces:
        - application/json
      responses:
        "200":
          schema:
            $ref: "#/definitions/Transaction"
          description: Transaction retrieved successfully
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Add Note to Transaction
      description: |
        API for adding a note to a specific transaction by providing the transaction ID and note data.
        Allows users to associate custom notes with their transactions, useful for adding comments or additional descriptions.
        Requires Bearer JWT token authorization for security.
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: accountId
          type: string
          description: Account ID
          required: true
        - in: path
          name: transactionId
          type: string
          description: Transaction ID
          required: true
        - in: body
          name: body
          description: Notes payload
          required: true
          schema:
            $ref: "#/definitions/UserTransaction"
      produces:
        - application/json
      responses:
        "200":
          schema:
            $ref: "#/definitions/Transaction"
          description: Note added successfully
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Update Transaction Note
      description: |
        API for updating the note of a specific transaction by providing the transaction ID and note data.
        Allows users to update the data of the note associated with a particular transaction.
        Requires Bearer JWT token authorization for security.
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: accountId
          type: string
          description: Account ID
          required: true
        - in: path
          name: transactionId
          type: string
          description: Transaction ID
          required: true
        - in: body
          name: body
          description: Notes payload
          required: true
          schema:
            $ref: "#/definitions/UserTransaction"
      produces:
        - application/json
      responses:
        "200":
          schema:
            $ref: "#/definitions/Transaction"
          description: Note updated successfully
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Delete Transaction Note
      description: |
        API for deleting the note of a specific transaction by providing the transaction ID.
        Allows users to remove a note previously associated with a transaction, if necessary.
        Bearer JWT token authorization is required to access this feature.
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: accountId
          type: string
          description: Account ID
          required: true
        - in: path
          name: transactionId
          type: string
          description: Transaction ID
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: Transaction note deleted successfully
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  UserTransaction:
    type: object
    properties:
      category:
        type: string
        description: Category
      notes:
        type: string
        description: Notes
  Transactions:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          transactions:
            type: array
            description: Array Of transactions
            items:
              $ref: "#/definitions/Transaction"
  Transaction:
    type: object
    properties:
      id:
        type: string
      userId:
        type: string
      date:
        type: string
        pattern: "yyyy-mm-dd"
      description:
        type: string
      amount:
        type: number
      balance:
        type: number
      transactionType:
        type: string
      category:
        type: string
      notes:
        type: string
